import { Property } from '../types';

// Demo & Example Properties for Anwar Najd Real Estate
// Note: These property listings and daily rental rates (120, 180, 250 SAR/day) are illustrative demo data
// and will be updated with official client properties once real listings are provided.
export const propertiesData: Property[] = [
  {
    id: 'anw-01',
    refNumber: 'ANW-1049',
    title: {
      ar: 'قصر مودرن فاخر بحي حطين النموذجي',
      en: 'Ultra-Luxury Modern Villa in Prestigious Hittin',
    },
    purpose: 'buy',
    type: 'villa',
    price: 9800000,
    priceFormatted: {
      ar: '9,800,000 ر.س',
      en: '9,800,000 SAR',
    },
    location: {
      districtAr: 'حطين',
      districtEn: 'Hittin',
      cityAr: 'الرياض',
      cityEn: 'Riyadh',
    },
    bedrooms: 6,
    bathrooms: 8,
    area: 750,
    featured: true,
    images: [
      '/images/property-villa-hittin.jpg',
      '/images/property-penthouse-malqa.jpg',
      '/images/hero-skyline.jpg',
    ],
    description: {
      ar: 'قصر عصري استثنائي بتصميم معماري فريد في أحد أرقى أحياء شمال الرياض (حطين). يتميز بواجهات حجرية زجاجية فاخرة، مسبح خاص ذو إطلالة بانورامية، تكييف مخفي متكامل، مصعد داخلي بانورامي، وأنظمة بيوت ذكية متكاملة (Smart Home) تتيح التحكم الكامل بالإضاءة والتكييف والأمان.',
      en: 'An exceptional contemporary residence showcasing bespoke modern architecture in prime Hittin, Northern Riyadh. Highlights include imported limestone and acoustic curtain glass, an infinity reflection pool, double-height ceilings, a panoramic Italian elevator, and full smart-home automation for climate and security.',
    },
    features: {
      ar: [
        'مسبح خاص مع نظام تدفئة وتبريد',
        'نظام تحكم ذكي كامل (Smart Home)',
        'مصعد داخلي فاخر يتسع لـ 6 أشخاص',
        'جناح ماستر ملكي مع غرفة ملابس وخزائن مدمجة',
        'مطبخ تحضيري إيطالي + مطبخ رئيسي متكامل',
        'غرفة سائق وخادمة مع دورات مياه خاصة',
        'موقف سيارات مظلل يتسع لـ 4 سيارات',
        'حديقة داخلية مع جلسة خارجية مجهزة بنظام رذاذ',
      ],
      en: [
        'Private heated and cooled swimming pool',
        'Complete automated smart home integration',
        'Panoramic passenger elevator (6-person capacity)',
        'Royal master suite with walk-in dressing salon',
        'Italian show kitchen + fully fitted dirty kitchen',
        'Dedicated driver and maid quarters with ensuites',
        'Covered parking garage for 4 vehicles',
        'Landscaped courtyard terrace with mist cooling',
      ],
    },
    yearBuilt: 2025,
    facade: {
      ar: 'شمالية شرقية على شارع 20م',
      en: 'North-East on 20m wide avenue',
    },
    specs: [
      { labelAr: 'المساحة', labelEn: 'Land Area', valueAr: '750 م²', valueEn: '750 m²' },
      { labelAr: 'مسطح البناء', labelEn: 'Built-up Area', valueAr: '1,150 م²', valueEn: '1,150 m²' },
      { labelAr: 'عمر العقار', labelEn: 'Property Age', valueAr: 'جديد (أول ساكن)', valueEn: 'Brand New' },
      { labelAr: 'الضمانات', labelEn: 'Warranties', valueAr: 'ضمانات شاملة تصل إلى 15 عاماً', valueEn: 'Up to 15-Year Structural Warranties' },
    ],
  },
  {
    id: 'anw-02',
    refNumber: 'ANW-2032',
    title: {
      ar: 'بنتهاوس ملكي دوبلكس مع تراس بانورامي بحي الملقا',
      en: 'Sky-High Royal Duplex Penthouse in Al Malqa',
    },
    purpose: 'buy',
    type: 'penthouse',
    price: 4350000,
    priceFormatted: {
      ar: '4,350,000 ر.س',
      en: '4,350,000 SAR',
    },
    location: {
      districtAr: 'الملقا',
      districtEn: 'Al Malqa',
      cityAr: 'الرياض',
      cityEn: 'Riyadh',
    },
    bedrooms: 4,
    bathrooms: 5,
    area: 420,
    featured: true,
    images: [
      '/images/property-penthouse-malqa.jpg',
      '/images/property-villa-hittin.jpg',
      '/images/about-corporate-lounge.jpg',
    ],
    description: {
      ar: 'شقة بنتهاوس دوبلكس فارهة في برج سكني راقٍ بحي الملقا، تتميز بإطلالة علوية خلابة على أفق مدينة الرياض. أرضيات رخامية إيطالية نخب أول، أسقف مرتفعة تمنح شعوراً بالاتساع والرحابة، تراس خارجي واسع مع جلسة شواء ومسبح جاكوزي خارجي مجهز.',
      en: 'An opulent duplex sky penthouse located in a prime boutique residential tower in Al Malqa. Offering breathtaking skyline panoramas, bookmatched Italian marble flooring, soaring double-height living areas, an expansive private rooftop entertaining terrace with heated jacuzzi, and private elevator access.',
    },
    features: {
      ar: [
        'تراس بانورامي خاص بمساحة 120 م²',
        'دخول خاص بمصعد مباشر للشقة (Private Keycard)',
        'صالون استقبال فسيح بإطلالة مفتوحة 180 درجة',
        'جاكوزي خارجي مع نظام تدليك مائي',
        'موقفين سيارة في القبو الخاص',
        'نادي صحي ولاونج مشترك للملاك في البرج',
      ],
      en: [
        '120 m² private landscaped terrace deck',
        'Direct private elevator card access to unit',
        'Expansive 180-degree panoramic reception salon',
        'Outdoor hydrotherapy heated jacuzzi spa',
        'Two private dedicated underground parking bays',
        'Residents-only wellness club and executive lounge',
      ],
    },
    yearBuilt: 2024,
    facade: {
      ar: 'إطلالة غربية وجنوبية مفتوحة',
      en: 'Open South-West city view',
    },
    specs: [
      { labelAr: 'المساحة الصافية', labelEn: 'Net Area', valueAr: '420 م²', valueEn: '420 m²' },
      { labelAr: 'الطابق', labelEn: 'Floor Level', valueAr: 'الدور 14 و 15', valueEn: '14th & 15th Floors' },
      { labelAr: 'رسوم اتحاد الملاك', labelEn: 'HOA Services', valueAr: 'شاملة الصيانة والأمن 24/7', valueEn: 'Includes 24/7 Concierge & Security' },
    ],
  },
  {
    id: 'anw-03',
    refNumber: 'ANW-3091',
    title: {
      ar: 'برج تجاري ومكاتب إدارية راقية بطريق الملك فهد',
      en: 'Corporate Commercial Tower Plaza on King Fahd Road',
    },
    purpose: 'rent',
    rentalPeriod: 'annual',
    type: 'commercial',
    price: 320000,
    priceFormatted: {
      ar: '320,000 ر.س / سنوياً',
      en: '320,000 SAR / Year',
    },
    location: {
      districtAr: 'العليا - طريق الملك فهد',
      districtEn: 'Al Olaya - King Fahd Rd',
      cityAr: 'الرياض',
      cityEn: 'Riyadh',
    },
    area: 580,
    featured: true,
    images: [
      '/images/property-commercial-tower.jpg',
      '/images/about-corporate-lounge.jpg',
      '/images/hero-skyline.jpg',
    ],
    description: {
      ar: 'مكاتب إدارية مفتوحة المساحة (Open Space) في برج تجاري ذكي من الفئة الممتازة (Grade A). تتمتع بواجهة زجاجية بانورامية، بنية تحتية رقمية متطورة للألياف الضوئية، بهو استقبال فندقي فخم مع خدمة أمنية واستقبال مدار الساعة، ومواقف سيارات مخصصة في القبو.',
      en: 'Prestigious corporate office floor plate situated in a Class-A intelligent commercial tower on King Fahd Road corridor. Features expansive curtain glass, high-speed fiber connectivity, five-star concierge reception lobby, card-access turnstiles, and ample reserved basement parking.',
    },
    features: {
      ar: [
        'تصنيف مبنى مكتبي فئة أولى (Grade A)',
        'بهو استقبال فخم مع كافيه ومساحات عمل مشتركة',
        'نظام إطفاء متطور ومراقبة أمنية 24/7',
        '8 مواقف سيارات مخصصة في القبو',
        'قاعات اجتماعات تنفيذية مشتركة ومجهزة',
        'قريب من محطة قطار الرياض والمراكز المالية',
      ],
      en: [
        'Grade-A corporate office building specification',
        'Grand double-height lobby with barista cafe',
        'Advanced HVAC, fire safety, and 24/7 CCTV surveillance',
        '8 allocated secure basement parking stalls',
        'State-of-the-art shared boardroom suites',
        'Walking distance to Riyadh Metro transit hub',
      ],
    },
    yearBuilt: 2023,
    facade: {
      ar: 'واجهة رئيسية على طريق الملك فهد',
      en: 'Direct frontage on King Fahd Road',
    },
    specs: [
      { labelAr: 'المساحة المكتبية', labelEn: 'Office Floor Area', valueAr: '580 م²', valueEn: '580 m²' },
      { labelAr: 'التهيئة', labelEn: 'Fit-out Condition', valueAr: 'تشطيب نصف مؤثث نخب أول', valueEn: 'Semi-Fitted Premium Grade' },
      { labelAr: 'نظام العقد', labelEn: 'Lease Terms', valueAr: 'عقد استثماري مرن موثق في إيجار', valueEn: 'Ejar-Certified Commercial Lease' },
    ],
  },
  {
    id: 'anw-04',
    refNumber: 'ANW-4112',
    title: {
      ar: 'فيلا مستقلة فاخرة بتشطيب مودرن بحي النرجس',
      en: 'Contemporary Architectural Villa in Al Narjis',
    },
    purpose: 'buy',
    type: 'villa',
    price: 5200000,
    priceFormatted: {
      ar: '5,200,000 ر.س',
      en: '5,200,000 SAR',
    },
    location: {
      districtAr: 'النرجس',
      districtEn: 'Al Narjis',
      cityAr: 'الرياض',
      cityEn: 'Riyadh',
    },
    bedrooms: 5,
    bathrooms: 6,
    area: 450,
    featured: true,
    images: [
      '/images/property-villa-narjis.jpg',
      '/images/about-corporate-lounge.jpg',
      '/images/property-villa-hittin.jpg',
    ],
    description: {
      ar: 'فيلا سكنية فاخرة في موقع استراتيجي هادئ بحي النرجس، قريبة من طريق الملك سلمان ومطار الملك خالد الدولي. تصميم مدروس يستغل الإضاءة الطبيعية مع فناء وسطي داخلي، تشطيبات عالية الجودة، ومرافق متكاملة تضمن الخصوصية التامة للعائلة.',
      en: 'A distinct modern standalone villa positioned on a quiet residential cul-de-sac in Al Narjis, offering quick access to King Salman Road and Riyadh Airport. Thoughtfully designed around a light-filled central courtyard, offering generous living spaces, top-tier insulation, and total family privacy.',
    },
    features: {
      ar: [
        'فناء داخلي مشجر مع إضاءة سماوية طبيعية',
        'مجلس رجال مستقل مع مغاسل رخامية ودورة مياه',
        'صالة عائلية واسعة بإطلالة على الحديقة الخلفية',
        'مطبخ ألماني مجهز بأجهزة كهرومنزيلية مدمجة',
        'غرفة غسيل وغرفة خادمة بالدور العلوي',
        'عوازل حرارية ومائية معتمدة وفق كود البناء السعودي',
      ],
      en: [
        'Central landscaped courtyard with natural skylight',
        'Independent guest salon with private marble washroom',
        'Expansive family living room facing private backyard',
        'Fitted German kitchen with integrated appliances',
        'Dedicated upper laundry room and maid room',
        'Certified insulation per Saudi Building Code standard',
      ],
    },
    yearBuilt: 2025,
    facade: {
      ar: 'شرقية على شارع 18م',
      en: 'East-facing on 18m street',
    },
    specs: [
      { labelAr: 'مساحة الأرض', labelEn: 'Land Area', valueAr: '450 م²', valueEn: '450 m²' },
      { labelAr: 'مسطح البناء', labelEn: 'Built Area', valueAr: '680 م²', valueEn: '680 m²' },
      { labelAr: 'شهادة إتمام البناء', labelEn: 'Building Certificate', valueAr: 'متوفرة ومعتمدة', valueEn: 'Fully Certified & Issued' },
    ],
  },
  {
    id: 'anw-05',
    refNumber: 'ANW-5044',
    title: {
      ar: 'شقة فاخرة مفروشة بالكامل للإيجار بحي الياسمين',
      en: 'Executive Furnished Residence in Al Yasmin',
    },
    purpose: 'rent',
    rentalPeriod: 'annual',
    type: 'apartment',
    price: 95000,
    priceFormatted: {
      ar: '95,000 ر.س / سنوياً',
      en: '95,000 SAR / Year',
    },
    location: {
      districtAr: 'الياسمين',
      districtEn: 'Al Yasmin',
      cityAr: 'الرياض',
      cityEn: 'Riyadh',
    },
    bedrooms: 3,
    bathrooms: 3,
    area: 185,
    featured: false,
    images: [
      '/images/property-apartment-yasmin.jpg',
      '/images/property-penthouse-malqa.jpg',
      '/images/about-corporate-lounge.jpg',
    ],
    description: {
      ar: 'شقة سكنية راقية مفروشة بأثاث إيطالي فاخر في مجمع سكني مغلق بحي الياسمين. تشتمل على مطبخ مجهز بالكامل بأحدث الأجهزة، دخول ذكي، نظام أمان ومراقبة، وموقف سيارة خاص في القبو.',
      en: 'Turnkey executive luxury apartment furnished with modern designer furniture in a prestigious gated residential community in Al Yasmin. Features an open-plan kitchen, smart door locks, secure basement parking, and clubhouse amenities.',
    },
    features: {
      ar: [
        'مفروشة بالكامل بأثاث فاخر وجديد',
        'مطبخ مجهز بالكامل بثلاجة وفرن وغسالة صحون',
        'دخول ذكي ببصمة ورمز سري',
        'شامل رسوم الصيانة والمياه',
        'موقف سيارة خاص مظلل',
      ],
      en: [
        'Fully furnished with pristine designer furniture',
        'Equipped kitchen with refrigerator, oven, dishwasher',
        'Keyless biometric smart door entry',
        'Inclusive of building maintenance and water dues',
        'Dedicated shaded basement parking space',
      ],
    },
    yearBuilt: 2024,
    facade: {
      ar: 'غربية مشمسة',
      en: 'Sunny West elevation',
    },
    specs: [
      { labelAr: 'المساحة', labelEn: 'Area', valueAr: '185 م²', valueEn: '185 m²' },
      { labelAr: 'عقد الإيجار', labelEn: 'Lease Type', valueAr: 'سنوي معتمد عبر منصة إيجار', valueEn: 'Annual Ejar Certified' },
    ],
  },
  {
    id: 'anw-06',
    refNumber: 'ANW-6088',
    title: {
      ar: 'أرض استثمارية تجارية وسكنية بحي الخير شمال الرياض',
      en: 'Prime Commercial & Mixed-Use Plot in Al Khair',
    },
    purpose: 'buy',
    type: 'land',
    price: 3600000,
    priceFormatted: {
      ar: '3,600,000 ر.س',
      en: '3,600,000 SAR',
    },
    location: {
      districtAr: 'الخير - شمال الرياض',
      districtEn: 'Al Khair - North Riyadh',
      cityAr: 'الرياض',
      cityEn: 'Riyadh',
    },
    area: 900,
    featured: false,
    images: [
      '/images/property-land-khair.jpg',
      '/images/hero-skyline.jpg',
      '/images/property-commercial-tower.jpg',
    ],
    description: {
      ar: 'أرض مميزة ذات موقع استثماري واعد في نطاق التطوير العمراني الجديد شمال الرياض. تقع على شارع تجاري رئيسي بعرض 30 متراً، صك إلكتروني رسمي ومخطط معتمد جاهز للتطوير التجاري أو المجمعات السكنية.',
      en: 'A high-potential investment and commercial land parcel located on the prime growth corridor of North Riyadh (Al Khair). Fronting a 30-meter commercial thoroughfare, electronic deed (Suk) ready, ideal for retail plazas or boutique residential developments.',
    },
    features: {
      ar: [
        'صك إلكتروني مفروز وجاهز للإفراغ الفوري',
        'شارع تجاري رئيسي بعرض 30 متر',
        'موقع واعد مع مشاريع البنية التحتية المحيطة',
        'أطوال متناسقة ومثالية للتطوير (30م × 30م)',
        'قريبة من المحاور الاستراتيجية الجديدة',
      ],
      en: [
        'Electronic clean title deed ready for immediate transfer',
        '30m wide prime commercial street frontage',
        'Rapidly appreciating strategic growth zone',
        'Optimal square parcel dimensions (30m x 30m)',
        'Immediate proximity to expanding highway arteries',
      ],
    },
    specs: [
      { labelAr: 'المساحة الإجمالية', labelEn: 'Total Plot Area', valueAr: '900 م²', valueEn: '900 m²' },
      { labelAr: 'سعر المتر التقريبي', labelEn: 'Price / m²', valueAr: '4,000 ر.س / م²', valueEn: '4,000 SAR / m²' },
      { labelAr: 'نوع الصك', labelEn: 'Title Deed', valueAr: 'إلكتروني محدث معتمد', valueEn: 'Official Electronic Suk' },
    ],
  },
  {
    id: 'anw-07',
    refNumber: 'ANW-7011',
    title: {
      ar: 'شقة فاخرة للإيجار الشهري بتصميم عصري بحي الملقا',
      en: 'Modern Furnished Monthly Apartment in Al Malqa',
    },
    purpose: 'rent',
    rentalPeriod: 'monthly',
    type: 'apartment',
    price: 28000,
    priceFormatted: {
      ar: '28,000 ر.س / شهرياً',
      en: '28,000 SAR / Month',
    },
    location: {
      districtAr: 'الملقا',
      districtEn: 'Al Malqa',
      cityAr: 'الرياض',
      cityEn: 'Riyadh',
    },
    bedrooms: 2,
    bathrooms: 2,
    area: 135,
    featured: false,
    images: [
      '/images/property-apartment-yasmin.jpg',
      '/images/property-penthouse-malqa.jpg',
      '/images/about-corporate-lounge.jpg',
    ],
    description: {
      ar: 'شقة سكنية مميزة ومفروشة بالكامل بنظام الإيجار الشهري في أرقى مجمعات حي الملقا. تشتمل على أثاث فندقي حديث، أجهزة كهربائية مدمجة، خدمة إنترنت فائق السرعة، ونظام دخول ذكي مع موقف خاص.',
      en: 'High-end turnkey furnished residence available on flexible monthly lease terms in prime Al Malqa. Includes boutique furnishings, high-speed fiber internet, smart access, and dedicated underground parking.',
    },
    features: {
      ar: [
        'إيجار شهري مرن بعقد موثق',
        'مفروشة بالكامل بأثاث مودرن حديث',
        'شامل باقة الإنترنت والصيانة الدورية',
        'دخول ذكي ومصعد خاص للمبنى',
        'موقع استراتيجي قريب من طريق أنس بن مالك',
      ],
      en: [
        'Flexible monthly lease authenticated on Ejar',
        'Fully furnished with designer contemporary furniture',
        'Inclusive of high-speed Wi-Fi & facility maintenance',
        'Keyless smart access & elevator',
        'Strategic location close to Anas Ibn Malik Road',
      ],
    },
    yearBuilt: 2024,
    facade: {
      ar: 'شمالية مشمسة',
      en: 'North-facing sunny terrace',
    },
    specs: [
      { labelAr: 'المساحة', labelEn: 'Area', valueAr: '135 م²', valueEn: '135 m²' },
      { labelAr: 'فترة الإيجار', labelEn: 'Rental Period', valueAr: 'إيجار شهري', valueEn: 'Monthly Rental' },
      { labelAr: 'الفرش', labelEn: 'Furnishing', valueAr: 'مفروشة بالكامل', valueEn: 'Fully Furnished' },
    ],
  },
  {
    id: 'anw-08',
    refNumber: 'ANW-7022',
    title: {
      ar: 'شقة تنفيذية للإيجار الشهري الفاخر بحي حطين',
      en: 'Executive Luxury Monthly Apartment in Hittin',
    },
    purpose: 'rent',
    rentalPeriod: 'monthly',
    type: 'apartment',
    price: 35000,
    priceFormatted: {
      ar: '35,000 ر.س / شهرياً',
      en: '35,000 SAR / Month',
    },
    location: {
      districtAr: 'حطين',
      districtEn: 'Hittin',
      cityAr: 'الرياض',
      cityEn: 'Riyadh',
    },
    bedrooms: 3,
    bathrooms: 3,
    area: 165,
    featured: false,
    images: [
      '/images/property-apartment-yasmin.jpg',
      '/images/property-penthouse-malqa.jpg',
      '/images/hero-skyline.jpg',
    ],
    description: {
      ar: 'شقة فاخرة للإيجار الشهري في قلب حي حطين الراقي. تشطيبات فندقية سوبر ديلوكس، تكييف مركزي متكامل، مطبخ إيطالي مجهز، صالة عائلية فسيحة وإطلالة هادئة بالقرب من بوليفارد رياض سيتي.',
      en: 'Executive designer flat for monthly rent in prime Hittin near Riyadh Boulevard. Features deluxe imported finishes, VRF concealed climate control, fitted Italian kitchen, and serene city views.',
    },
    features: {
      ar: [
        'نظام إيجار شهري معتمد وسلس',
        'صالة استقبال واسعة ومطبخ مفتوح',
        'أجهزة مطبخ متكاملة وغسالة ملابس',
        'موقف سيارة خاص تحت المظلة',
        'حراسة وأمن على مدار الساعة',
      ],
      en: [
        'Seamless monthly rental platform integration',
        'Spacious open-concept living and dining area',
        'Integrated gourmet kitchen appliances',
        'Reserved covered parking space',
        '24/7 on-site building security',
      ],
    },
    yearBuilt: 2025,
    facade: {
      ar: 'شرقية على شارع رئيسي هادئ',
      en: 'East-facing on prime residential road',
    },
    specs: [
      { labelAr: 'المساحة', labelEn: 'Area', valueAr: '165 م²', valueEn: '165 m²' },
      { labelAr: 'فترة الإيجار', labelEn: 'Rental Period', valueAr: 'إيجار شهري', valueEn: 'Monthly Rental' },
      { labelAr: 'التكييف', labelEn: 'Air Conditioning', valueAr: 'مركزي مخفي', valueEn: 'Concealed Central HVAC' },
    ],
  },
  {
    id: 'anw-09',
    refNumber: 'ANW-7033',
    title: {
      ar: 'شقة عائلية فاخرة للإيجار السنوي بحي العقيق',
      en: 'Premium Family Annual Apartment in Al Aqiq',
    },
    purpose: 'rent',
    rentalPeriod: 'annual',
    type: 'apartment',
    price: 45000,
    priceFormatted: {
      ar: '45,000 ر.س / سنوياً',
      en: '45,000 SAR / Year',
    },
    location: {
      districtAr: 'العقيق',
      districtEn: 'Al Aqiq',
      cityAr: 'الرياض',
      cityEn: 'Riyadh',
    },
    bedrooms: 3,
    bathrooms: 2,
    area: 150,
    featured: false,
    images: [
      '/images/property-apartment-yasmin.jpg',
      '/images/property-fallback.jpg',
      '/images/about-corporate-lounge.jpg',
    ],
    description: {
      ar: 'شقة عائلية مشرحة بتوزيع هندسي ممتاز للإيجار السنوي بحي العقيق بالقرب من مركز الملك عبدالله المالي (KAFD). موقع مميز وخدمات متكاملة ومدارس ومرافق تجارية.',
      en: 'Bright and well-proportioned annual family apartment in Al Aqiq, moments from KAFD. Features functional layout, quality sanitaryware, and proximity to international schools and shopping hubs.',
    },
    features: {
      ar: [
        'عقد إيجار سنوي موثق عبر منصة إيجار',
        'قريبة جداً من مركز الملك عبدالله المالي',
        'مصعد حديث ودخول بكارت إلكتروني',
        'مطبخ راكب ومكيفات سبليت حديثة',
        'موقف مخصص وخزان مياه مستقل',
      ],
      en: [
        'Official annual lease verified on Ejar',
        'Walking proximity to King Abdullah Financial District',
        'Modern elevator and digital keycard entry',
        'Fitted kitchen cabinets and efficient AC units',
        'Reserved parking and dedicated water meter',
      ],
    },
    yearBuilt: 2023,
    facade: {
      ar: 'جنوبية على شارع 15م',
      en: 'South-facing on 15m street',
    },
    specs: [
      { labelAr: 'المساحة', labelEn: 'Area', valueAr: '150 م²', valueEn: '150 m²' },
      { labelAr: 'فترة الإيجار', labelEn: 'Rental Period', valueAr: 'إيجار سنوي', valueEn: 'Annual Rental' },
      { labelAr: 'الدفعات', labelEn: 'Payment Terms', valueAr: 'دفعتين ميسرة', valueEn: 'Flexible Bi-Annual' },
    ],
  },
  {
    id: 'anw-10',
    refNumber: 'ANW-7044',
    title: {
      ar: 'استراحة خاصة VIP للإيجار اليومي والمناسبات شمال الرياض',
      en: 'VIP Private Resort & Chalet for Daily Rental',
    },
    purpose: 'rent',
    rentalPeriod: 'daily',
    dailyPrice: 250,
    type: 'resort',
    price: 250,
    priceFormatted: {
      ar: '250 ريال / يوم',
      en: '250 SAR / day',
    },
    location: {
      districtAr: 'الخير - شمال الرياض',
      districtEn: 'Al Khair - North Riyadh',
      cityAr: 'الرياض',
      cityEn: 'Riyadh',
    },
    bedrooms: 2,
    bathrooms: 3,
    area: 450,
    featured: false,
    images: [
      '/images/property-villa-hittin.jpg',
      '/images/hero-skyline.jpg',
      '/images/property-fallback.jpg',
    ],
    description: {
      ar: 'استراحة خاصة راقية بنظام الإيجار اليومي للمناسبات الخاصة والاجتماعات العائلية الرفيعة شمال الرياض. مجهزة بمسبح، مسطحات خضراء وجلسات خارجية مع مرافق ضيافة فندقية متكاملة.',
      en: 'A secluded luxury chalet and resort venue available for daily rental packages. Ideal for private gatherings, corporate retreats, and family occasions with swimming pool and lush outdoor pergolas.',
    },
    features: {
      ar: [
        'حجز يومي مرن مع خدمات الضيافة',
        'مسبح خارجي خاص مع شلال جداري',
        'جلسات خارجية مجهزة بأنظمة رذاذ وإضاءة ليلية',
        'صالة ضيافة رئيسية مجهزة بنظام صوتي وعرض',
        'خصوصية تامة ومواقف خارجية واسعة',
      ],
      en: [
        'Flexible daily booking with concierge support',
        'Private outdoor pool with water feature',
        'Outdoor mist-cooled landscaped pergola',
        'Grand salon with audio-visual equipment',
        'Full privacy and expansive parking forecourt',
      ],
    },
    yearBuilt: 2024,
    facade: {
      ar: 'واجهة مفتوحة على مزارع شمال الرياض',
      en: 'Open panorama in North Riyadh',
    },
    specs: [
      { labelAr: 'المساحة', labelEn: 'Area', valueAr: '450 م²', valueEn: '450 m²' },
      { labelAr: 'فترة الإيجار', labelEn: 'Rental Period', valueAr: 'إيجار يومي', valueEn: 'Daily Rental' },
      { labelAr: 'سعر الإيجار اليومي', labelEn: 'Daily Rental Price', valueAr: '250 ريال / يوم', valueEn: '250 SAR / day' },
      { labelAr: 'المرافق', labelEn: 'Amenities', valueAr: 'مسبح + حدائق + مجلس ضيافة', valueEn: 'Pool, Lawns & Salon' },
    ],
  },
  {
    id: 'anw-11',
    refNumber: 'ANW-7055',
    title: {
      ar: 'فيلا سكنية فاخرة للإيجار اليومي للمناسبات بحي الصحافة',
      en: 'Luxury Villa Suite for Daily Rental in Al Sahafa',
    },
    purpose: 'rent',
    rentalPeriod: 'daily',
    dailyPrice: 180,
    type: 'villa',
    price: 180,
    priceFormatted: {
      ar: '180 ريال / يوم',
      en: '180 SAR / day',
    },
    location: {
      districtAr: 'الصحافة',
      districtEn: 'Al Sahafa',
      cityAr: 'الرياض',
      cityEn: 'Riyadh',
    },
    bedrooms: 4,
    bathrooms: 5,
    area: 500,
    featured: false,
    images: [
      '/images/property-villa-narjis.jpg',
      '/images/property-villa-hittin.jpg',
      '/images/about-corporate-lounge.jpg',
    ],
    description: {
      ar: 'فيلا فاخرة للإيجار اليومي مصممة لاستضافة الوفود التنفيذية والمناسبات الراقية بحي الصحافة. تتميز بمجالس رحبة، صالونات استقبال فخمة، وحديقة داخلية مجهزة بأعلى المعايير.',
      en: 'High-end residential villa available for exclusive daily rental and executive delegation stays in Al Sahafa. Offers expansive reception halls, luxury suites, and manicured courtyard grounds.',
    },
    features: {
      ar: [
        'نظام إيجار يومي للشركات والعائلات',
        'مجالس استقبال ملكية رحبة',
        'تجهيزات فندقية كاملة تشمل الفرش والمستلزمات',
        'مدخل سيارات خاص مع كراج مغلق',
        'خدمة مساعدة وضيافة عند الطلب',
      ],
      en: [
        'Daily rental framework for corporate & VIP stays',
        'Grand royal entertainment majlis',
        'Five-star hotel linens and amenities provided',
        'Private driveway with secured garage',
        'Concierge and hospitality support on request',
      ],
    },
    yearBuilt: 2024,
    facade: {
      ar: 'شمالية على شارع 20م',
      en: 'North on 20m wide street',
    },
    specs: [
      { labelAr: 'المساحة', labelEn: 'Area', valueAr: '500 م²', valueEn: '500 m²' },
      { labelAr: 'فترة الإيجار', labelEn: 'Rental Period', valueAr: 'إيجار يومي', valueEn: 'Daily Rental' },
      { labelAr: 'سعر الإيجار اليومي', labelEn: 'Daily Rental Price', valueAr: '180 ريال / يوم', valueEn: '180 SAR / day' },
      { labelAr: 'الاستخدام', labelEn: 'Usage', valueAr: 'ضيافة خاصة ومناسبات', valueEn: 'VIP Private & Corporate' },
    ],
  },
  {
    id: 'anw-12',
    refNumber: 'ANW-7066',
    title: {
      ar: 'دور أرضي فاخر مع حديقة للإيجار السنوي بحي النرجس',
      en: 'Luxury Ground Floor with Garden in Al Narjis',
    },
    purpose: 'rent',
    rentalPeriod: 'annual',
    type: 'ground_floor',
    price: 48000,
    priceFormatted: {
      ar: '48,000 ر.س / سنوياً',
      en: '48,000 SAR / Year',
    },
    location: {
      districtAr: 'النرجس',
      districtEn: 'Al Narjis',
      cityAr: 'الرياض',
      cityEn: 'Riyadh',
    },
    bedrooms: 3,
    bathrooms: 3,
    area: 220,
    featured: false,
    images: [
      '/images/property-villa-narjis.jpg',
      '/images/property-apartment-yasmin.jpg',
      '/images/property-fallback.jpg',
    ],
    description: {
      ar: 'دور أرضي مستقل مع فناء خارجي وحديقة خاصة للإيجار السنوي بحي النرجس شمال الرياض. مدخل خاص، مجلس رحب، مطبخ راكب وصالة عائلية تطل مباشرة على الحديقة.',
      en: 'Independent ground-floor residence with private garden courtyard available for annual lease in Al Narjis. Independent private entrance, spacious majlis, and fitted kitchen.',
    },
    features: {
      ar: [
        'عقد إيجار سنوي معتمد عبر منصة إيجار',
        'مدخل سيارة وحوش خاص مع حديقة',
        'مجلس رجال مستقل مع مغاسل رخامية',
        'مطبخ راكب ومكيفات موفرة للطاقة',
        'عداد كهرباء ومياه مستقل',
      ],
      en: [
        'Annual authenticated Ejar tenancy contract',
        'Private gated driveway and manicured garden',
        'Independent guest majlis with marble washroom',
        'Fitted kitchen and energy-saving inverter ACs',
        'Independent electricity and water utility meters',
      ],
    },
    yearBuilt: 2024,
    facade: {
      ar: 'شرقية على شارع 18م',
      en: 'East on 18m residential street',
    },
    specs: [
      { labelAr: 'المساحة', labelEn: 'Area', valueAr: '220 م²', valueEn: '220 m²' },
      { labelAr: 'فترة الإيجار', labelEn: 'Rental Period', valueAr: 'إيجار سنوي', valueEn: 'Annual Rental' },
      { labelAr: 'المدخل', labelEn: 'Entrance', valueAr: 'مدخل مستقل خاص', valueEn: 'Private Independent Entry' },
    ],
  },
  {
    id: 'anw-13',
    refNumber: 'ANW-7077',
    title: {
      ar: 'شقة مع السطح بتراس خاص للإيجار السنوي بحي النخيل',
      en: 'Luxury Rooftop Apartment with Terrace in Al Nakheel',
    },
    purpose: 'rent',
    rentalPeriod: 'annual',
    type: 'roof_apartment',
    price: 65000,
    priceFormatted: {
      ar: '65,000 ر.س / سنوياً',
      en: '65,000 SAR / Year',
    },
    location: {
      districtAr: 'النخيل',
      districtEn: 'Al Nakheel',
      cityAr: 'الرياض',
      cityEn: 'Riyadh',
    },
    bedrooms: 3,
    bathrooms: 3,
    area: 195,
    featured: false,
    images: [
      '/images/property-penthouse-malqa.jpg',
      '/images/property-apartment-yasmin.jpg',
      '/images/hero-skyline.jpg',
    ],
    description: {
      ar: 'شقة روف مودرن مع سطح خاص وتراس بانورامي مطل للإيجار السنوي بحي النخيل الراقي. موقع استثنائي بالقرب من جامعة الملك سعود والمحاور الحيوية بالرياض.',
      en: 'Boutique modern rooftop apartment with expansive private open-air terrace for annual rent in Al Nakheel. Proximity to King Saud University and major arterial expressways.',
    },
    features: {
      ar: [
        'سطح وتراس خاص واسع بإطلالة بانورامية',
        'عقد سنوي معتمد عبر منصة إيجار',
        'دخول ذكي ومصعد يصل مباشرة للدور',
        'مطبخ ألماني مجهز وتكييف مخفي',
        'موقف سيارة خاص في القبو',
      ],
      en: [
        'Expansive private rooftop terrace with views',
        'Official annual Ejar certified tenancy',
        'Keyless entry and elevator to private landing',
        'German fitted kitchen & concealed HVAC',
        'Designated basement garage parking bay',
      ],
    },
    yearBuilt: 2025,
    facade: {
      ar: 'جنوبية غربية بإطلالة مفتوحة',
      en: 'South-West panoramic view',
    },
    specs: [
      { labelAr: 'المساحة', labelEn: 'Area', valueAr: '195 م²', valueEn: '195 m²' },
      { labelAr: 'فترة الإيجار', labelEn: 'Rental Period', valueAr: 'إيجار سنوي', valueEn: 'Annual Rental' },
      { labelAr: 'التراس', labelEn: 'Terrace Area', valueAr: 'سطح خاص 60 م²', valueEn: 'Private 60 m² Rooftop' },
    ],
  },
  {
    id: 'anw-14',
    refNumber: 'ANW-7088',
    title: {
      ar: 'شقة استوديو فندقية فاخرة للإيجار اليومي بحي العليا',
      en: 'Boutique Hotel Studio Suite for Daily Rental in Al Olaya',
    },
    purpose: 'rent',
    rentalPeriod: 'daily',
    dailyPrice: 120,
    type: 'apartment',
    price: 120,
    priceFormatted: {
      ar: '120 ريال / يوم',
      en: '120 SAR / day',
    },
    location: {
      districtAr: 'العليا',
      districtEn: 'Al Olaya',
      cityAr: 'الرياض',
      cityEn: 'Riyadh',
    },
    bedrooms: 1,
    bathrooms: 1,
    area: 75,
    featured: false,
    images: [
      '/images/property-apartment-yasmin.jpg',
      '/images/property-penthouse-malqa.jpg',
      '/images/hero-skyline.jpg',
    ],
    description: {
      ar: 'استوديو فندقي فاخر مؤثث بأرقى المعايير بنظام الإيجار اليومي في قلب حي العليا بالرياض. مجهز بإنترنت فائق السرعة، دخول ذكي، وخدمات تنظيف فندقية.',
      en: 'Boutique executive hotel studio suite available on a flexible daily rental basis in central Al Olaya. Features high-speed fiber Wi-Fi, keyless smart entry, and hotel housekeeping.',
    },
    features: {
      ar: [
        'نظام إيجار يومي مرن مع دخول ذاتي ذكي',
        'موقع استراتيجي وسط العليا قريب من الأبراج ومحطة المترو',
        'مفروش بالكامل بأثاث فندقي 5 نجوم',
        'مطبخ تحضيري مجهز وآلة قهوة',
        'موقف سيارة خاص وخدمة أمنية',
      ],
      en: [
        'Flexible daily rental with seamless smart self check-in',
        'Central Al Olaya location near financial towers and metro',
        'Fully furnished with five-star hospitality fittings',
        'Kitchenette with espresso station and appliances',
        'Dedicated parking bay with 24/7 security',
      ],
    },
    yearBuilt: 2024,
    facade: {
      ar: 'واجهة شمالية بإطلالة على أبراج العليا',
      en: 'North-facing with city skyline panorama',
    },
    specs: [
      { labelAr: 'المساحة', labelEn: 'Area', valueAr: '75 م²', valueEn: '75 m²' },
      { labelAr: 'فترة الإيجار', labelEn: 'Rental Period', valueAr: 'إيجار يومي', valueEn: 'Daily Rental' },
      { labelAr: 'سعر الإيجار اليومي', labelEn: 'Daily Rental Price', valueAr: '120 ريال / يوم', valueEn: '120 SAR / day' },
      { labelAr: 'الدخول', labelEn: 'Check-in', valueAr: 'دخول ذاتي ذكي 24/7', valueEn: 'Smart Self Check-in 24/7' },
    ],
  },
];
